config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  resources :users
  resources :posts do
    resources :comments
end
 root 'posts#index'

   resources :users  do
    collection do
      get :search

    end
  end

  resources :friendships

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :friendships
  has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

	has_one :profile
	has_many :posts
	has_many :comments
	has_attached_file :image, styles: { large: "600x600", medium: "300x300#", thumb: "100x100#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :image

  def self.search(search)
    if search
       @users = User.where('firstname LIKE ?', "%#{@search}%")
     
    else
      find(:all)
    end
  end


 

def active?
  !!active
end

def inactive_message
  "Sorry, this account has been deactivated."
end

def soft_delete
  # assuming you have deleted_at column added already
  update_attribute(:deleted_at, Time.current)
  update_attribute(:active, false)

end

end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname,:lastname,:email, :password, :password_confirmation, :image) }
    devise_parameter_sanitizer.for(:sign_in) << [:email, :remember_me]
  end

  protect_from_forgery with: :exception

  def update_resource(resource, params)
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
      @users = User.search(params[:search])
  end

  def search
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order("created_at DESC")
    end
  end


  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_navigational_format?
    respond_with_navigational(resource){ redirect_to   after_sign_out_path_for(resource_name) }
  end
  	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	before_action :find_post
	before_action :find_comment, only: [:edit, :update, :destroy]
	before_action :authenticate_user!

	def create
		@comment = @post.comments.create(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end

	private

    def comment_params
      params.require(:comment).permit(:comment_text)
    end

	def find_post
		@post = Post.find(params[:post_id])			
	end

	def find_comment
		@post = @post.comments.find(params[:id])
	end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def create
 		 @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
  			if @friendship.save
   				 flash[:notice] = "Added friend."
    			 redirect_to root_url
 			else
    			 flash[:notice] = "Unable to add friend."
    			 redirect_to root_url
  			end
	end

	def destroy
 		@friendship = current_user.friendships.find(params[:id])
  		@friendship.destroy
  		flash[:notice] = "Removed friendship."
  		redirect_to current_user
	end

	def show
		@friendship = current_user.friendships.find(params[:id])
		@user = @friendship.friend		
    @posts = @user.posts
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show] 
	
	def index
		@posts = Post.all.order("created_at DESC")

		#	ids = current_user.friends.pluck(:id) << current_user.id
		#	@posts = Post.where(user_id: ids)
	end

	def show
		
	end

	def new
		@post = current_user.posts.build
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def update
	 	if @post.update(post_params)
			redirect_to post_path
		else
			render 'edit'
		end
	end

	def destroy
   		@post.destroy
   		redirect_to root_path
  end

	private
		def post_params
			params.require(:post).permit(:status)
		end

		def find_post
			@post = Post.find(params[:id])
		end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

	def edit
    @user = User.find(params[:id])
  	end

  	  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_navigational_format?
    respond_with_navigational(resource){ redirect_to   after_sign_out_path_for(resource_name) }
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # def new
  #   super
  # end

end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
   @search = params[:search]  
    @users = User.search(@search) 
  end

  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts
  end

  def add_friend
    
  end
  
  def remove_friend
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
		
	<p class="commenttext"><%= comment.comment_text%></p>
	<p class="comment-posted-by">Posted by <%= comment.user.email if comment.user%>

	<div class="links">
		<% if user_signed_in? %>
			<% if comment.user_id == current_user.id %>
				<%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
				<%= link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: { confirm: "Are you sure?"} %>
			<% end %>
		<% end %>
		
	</div>
	

</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
	<%= f.input :comment_text, label: false, :class => 'commentField' %>
	<%= f.button :submit, :class => 'btn-custom'%>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@post, @comment]) do |f| %>
	<%= f.input :comment_text, label: "Comment" %>
	<%= f.button :submit %>
<% end %>

app/views/friendships/show.html.erb
<html><body>



<section id = "profileHeader">
<h1 align="center"><%= @user.firstname %> <%= @user.lastname %></h1>
	<div class="profileimg">
		<center>
		<%= image_tag @user.image.url(:medium), class: "img-circle" %>
	</div>
</section>

<section id = "allposts">
<div class = "postsLabel">
<h2 align="center"><%= @user.firstname %>'s Posts</h2>
</div>
	
	<% @posts.each do |post| %>
	<center>
	<div class="col-md-4">
 	<h2 class="status"><%= post.status %></h2>
 	<%= link_to "View Comments", post_path(post), class: "btn-viewcomment" %> 
 	</div> 
    <% end %>
</section>

<section id = "friends">
<div class = "friendsLabel">
<h2 align="center"><%= @user.firstname %>'s Friends</h2>
</div>
	 <% for user in @user.friends %>
 	 <%= image_tag user.image.url(:medium), class: "img-circle" %>
 	 <%= link_to user.firstname, user %>
  <% end %>  
</section>


<h2>Users Who Have Befriended <%= @friendship.friend.firstname %> </h2> 
<ul>
  <% for user in @user.inverse_friends %>
  <%= image_tag user.image.url(:medium), class: "img-circle" %>
   <%= link_to user.firstname, user %>
  <% end %>
</ul>

app/views/home/front.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>Buddler.</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
     <!-- FONTAWESOME STYLE CSS -->
     <link href="assets/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLE CSS -->
    <link href="assets/css/style.css" rel="stylesheet" />
</head>
<body > 
   
        <div class="navbar navbar-inverse navbar-fixed-top " >
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#" ><strong style="">Buddler.</strong> </a>
            </div>
            
            <div class="navbar-collapse collapse move-me">
                <ul class="nav navbar-nav navbar-right set-links">
                    <% if user_signed_in? %>

                        <li><%= link_to current_user.email, edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete' %></li>
                         <li><%= link_to "Update Status", new_post_path %></li>
                    <% else %>
                        <li><%= link_to "Sign Up", new_user_registration_path %> </li>
                        <li><%= link_to "Sign In", new_user_session_path %> </li>
                    <% end %>
                  
                </ul>
            </div>

        </div>
    </div>
    <!--MENU SECTION END-->
    <div class="container">

        <%= yield %>        
    </div>
    <!--HOME SECTION END-->
     <section id="search-domain" >
        <div class="container">
            <div class="row">
        <div class="col-md-8">
            <input type="text" class="form-control input-cls"/>
        </div>
                <div class="col-md-4">
                    <input type="button" class="btnsearch"  value="SEARCH A BUDDY" />
                </div>
            </div>
        </div>
    </section>

        

<!--SEARCH SECTION END-->
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
          <%= f.input :status, :class => 'statusField' %>
          <%= f.button :submit, :class => 'statusPostBtn' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Status</h1>
 
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<center>
 <div class="col-md-4">

 <div class="post">
 <h2 class="status"><%= post.status %></h2>
 <%= link_to "View Comments", post_path(post), class: "btn-viewcomment" %> 
 </div>
  </div>
  
<% end %>

app/views/posts/new.html.erb
<div class="newpost">
<center>	
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<html><body>
	<div class="showstatus">		
	
		<div class="statusview"><%= @post.status %></div>
		<div class="status-posted-by">Posted by <%= @post.user.email  %> <%= time_ago_in_words(@post.created_at) %>
		ago </h4>

		<h2 class="commentlbl">Comments:</h2>
		<%=  render @post.comments %>

		<h3 class="commentreply">Reply to comment</h3>
		<%= render 'comments/form' %>

		<div class="links btn-group">
			<%= link_to "Back", root_path, class: "btn btn-default" %>
			<% if user_signed_in? %>
				<% if @post.user_id == current_user.id %>
					<%= link_to "Edit", edit_post_path(@post), class: "btn btn-default" %>
					<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"  %>
				<% end %>
			<% end %>

		</div>
		</div>
	</div>
</body>
</html>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/show.html.erb
<html><body>

<%= link_to "Add as Friend", friendships_path(:friend_id => @user), :method => :post, :class => "addBtn" %>

<section id = "profileHeader">
<h1 align="center"><%= @user.firstname %> <%= @user.lastname %></h1>
	<div class="profileimg">
		<center>
		<%= image_tag @user.image.url(:medium), class: "img-circle" %>
	</div>
</section>

<section id = "allposts">
<div class = "postsLabel">
<h2 align="center"><%= @user.firstname %>'s Posts</h2>
</div>
	<% @posts.each do |post| %>
	<center>
	<div class="col-md-4">
 	<h2 class="status"><%= post.status %></h2>
 	<%= link_to "View Comments", post_path(post), class: "btn-viewcomment" %> 
 	</div> 
    <% end %>
</section>

<section id = "friends">
<div class = "friendsLabel">
<br>
<h2 align="center"><%= @user.firstname %>'s Friends</h2>
</div>

<div class = "friendsList">
	<% for friendship in @user.friendships %>
  		<%= image_tag friendship.friend.image.url(:thumb), :class => "friendImage" %>
    	<%= link_to "#{friendship.friend.firstname} #{friendship.friend.lastname}", friendship, :class => "friendName"%>
		(<%= link_to "remove", friendship, :method => :delete %>)
  	<% end %> 
  	</div> 
<div class = "postsLabel">
<br>
<h2>Users Who Have Befriended <%= @user.firstname %></h2>
</div>
<ul>
  <% for user in @user.inverse_friends %>
  <%= image_tag user.image.url(:thumb), :class => "friendImage" %>
  <%= link_to "#{user.firstname} #{user.lastname}", user, :class => "friendName" %>
  <% end %>
</ul>
</section> 