config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  resources :users
  resources :posts do
    resources :comments
end
 root 'posts#index'

   resources :users  do
    collection do
      get :search

    end
  end

  resources :friendships

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :friendships
  has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

	has_one :profile
	has_many :posts
	has_many :comments
	has_attached_file :image, styles: { large: "600x600", medium: "300x300#", thumb: "100x100#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :image

  def self.search(search)
    if search
       @users = User.where('firstname LIKE ?', "%#{@search}%")
     
    else
      find(:all)
    end
  end


 

def active?
  !!active
end

def inactive_message
  "Sorry, this account has been deactivated."
end

def soft_delete
  # assuming you have deleted_at column added already
  update_attribute(:deleted_at, Time.current)
  update_attribute(:active, false)

end

end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname,:lastname,:email, :password, :password_confirmation, :image) }
    devise_parameter_sanitizer.for(:sign_in) << [:email, :remember_me]
  end

  protect_from_forgery with: :exception

  def update_resource(resource, params)
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
      @users = User.search(params[:search])
  end

  def search
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order("created_at DESC")
    end
  end


  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_navigational_format?
    respond_with_navigational(resource){ redirect_to   after_sign_out_path_for(resource_name) }
  end
  	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	before_action :find_post
	before_action :find_comment, only: [:edit, :update, :destroy]
	before_action :authenticate_user!

	def create
		@comment = @post.comments.create(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end

	private

    def comment_params
      params.require(:comment).permit(:comment_text)
    end

	def find_post
		@post = Post.find(params[:post_id])			
	end

	def find_comment
		@post = @post.comments.find(params[:id])
	end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def create
 		 @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
  			if @friendship.save
   				 flash[:notice] = "Added friend."
    			 redirect_to root_url
 			else
    			 flash[:notice] = "Unable to add friend."
    			 redirect_to root_url
  			end
	end

	def destroy
 		@friendship = current_user.friendships.find(params[:id])
  		@friendship.destroy
  		flash[:notice] = "Removed friendship."
  		redirect_to current_user
	end

	def show
		@friendship = current_user.friendships.find(params[:id])
		@user = @friendship.friend		
    @posts = @user.posts
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show] 
	
	def index
		@posts = Post.all.order("created_at DESC")

		#	ids = current_user.friends.pluck(:id) << current_user.id
		#	@posts = Post.where(user_id: ids)
	end

	def show
		
	end

	def new
		@post = current_user.posts.build
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def update
	 	if @post.update(post_params)
			redirect_to post_path
		else
			render 'edit'
		end
	end

	def destroy
   		@post.destroy
   		redirect_to root_path
  end

	private
		def post_params
			params.require(:post).permit(:status)
		end

		def find_post
			@post = Post.find(params[:id])
		end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # def new
  #   super
  # end

end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
   @search = params[:search]  
    @users = User.search(@search) 
  end

  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts
  end

  def add_friend
    
  end
  
  def remove_friend
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />

  <title>Buddler.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>

  <link href="assets/css/bootstrap.css" rel="stylesheet" />
  <link href="assets/css/font-awesome.css" rel="stylesheet" />    
  <link href="assets/css/style.css" rel="stylesheet" />
  <%= csrf_meta_tags %>
</head>
<body > 
   
        <div class="navbar navbar-inverse navbar-fixed-top " >
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#" ><strong style="">Buddler.</strong> </a>
            </div>
            
            <div class="navbar-collapse collapse move-me">
                <ul class="nav navbar-nav navbar-right set-links">

                    <% if user_signed_in? %>
                      <li><%= link_to "Home", new_user_session_path %></li>
                      <li><%= link_to "Add new post", new_post_path %></li>
                      <li><%= link_to "My Profile", current_user %></li>
                      <li><%= link_to('Edit Profile', edit_user_registration_path(@current_user))%></li>
                      <li><%= link_to "Logout", destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: 'delete' %></li>
                         
                    <% else %>
                        <li><%= link_to "Sign Up", new_user_registration_path %> </li>
                        <li><%= link_to "Sign In", new_user_session_path %> </li>
                    <% end %>
                  
                </ul>
            </div>

           <div class="searchUser">
             <% if user_signed_in? %>
                <%= form_tag users_path, :method => 'get' do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Search a Buddy :)", class: "searchField" %>
                  <%= submit_tag "Search", class: "searchBtn", :firstname => nil  %>
                <% end %> 
             <% end %>
        </div>

        </div>

    </div>
    <hr>
    <!--MENU SECTION END-->
    

    <% if user_signed_in? %>
  
    <section id="home-sec1">
    

        <%= yield %>
      
    </section>
 
    <% else %>
      <section id="home-sec">
        <div class="overlay text-center">
      
        </div>
    </section>
    <% end %>

    
     <% if user_signed_in? %>
      
    <% else %>
     <section id="search-domain" >
      <div class="container">
            <div class="row">
        <div class="col-md-8">
           <%= form_tag(users_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], class: "form-control input-cls" %>
        </div>
                <div class="col-md-4">
                   <%= submit_tag "SEARCH A BUDDY", class: "btnsearch"  %>
                </div>
            </div>
        </div>
        <% end %>
    </section>
    <% end %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buddler: Log In</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>